# filename: async-ingestion.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import asyncio
import json
from pathlib import Path

from langchain_community.document_loaders import (
    PyPDFLoader,
    TextLoader,
    WebBaseLoader,
)
from langchain_text_splitters import RecursiveCharacterTextSplitter

DATA_DIR = Path("Static Data")
WEB_URL_FILE = Path("Static Data/Web URLS.txt")
OUTPUT_FILE = Path("processed/chunks.json")

MAX_CONCURRENCY = 5
SUPPORTED_SUFFIXES = {".txt",".docx", ".md", ".pdf"}


def read_web_urls() -> list[str]:
    if not WEB_URL_FILE.exists():
        return []

    return [
        line.strip()
        for line in WEB_URL_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def load_local_file_sync(path: Path):
    suffix = path.suffix.lower()

    if suffix in {".txt", ".md", ".docx"}:
        loader = TextLoader(str(path), encoding="utf-8")
    elif suffix == ".pdf":
        loader = PyPDFLoader(str(path))
    else:
        return []

    documents = loader.load()

    for document in documents:
        document.metadata.update(
            {
                "source_type": "local_file",
                "source_ref": str(path),
            }
        )

    return documents


def load_web_page_sync(url: str):
    documents = WebBaseLoader(url).load()

    for document in documents:
        document.metadata.update(
            {
                "source_type": "website",
                "source_ref": url,
            }
        )

    return documents


async def load_source(
    source: str,
    source_type: str,
    semaphore: asyncio.Semaphore,
):
    async with semaphore:
        try:
            if source_type == "website":
                return await asyncio.to_thread(load_web_page_sync, source)

            return await asyncio.to_thread(
                load_local_file_sync,
                Path(source),
            )
        except Exception as error:
            print(f"Failed to load {source}: {error}")
            return []


async def ingest():
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    local_sources = [
        path
        for path in DATA_DIR.rglob("*")
        if path.is_file()
        and path.suffix.lower() in SUPPORTED_SUFFIXES
    ]

    web_sources = read_web_urls()
    semaphore = asyncio.Semaphore(MAX_CONCURRENCY)

    tasks = [
        load_source(str(path), "local_file", semaphore)
        for path in local_sources
    ]

    tasks.extend(
        load_source(url, "website", semaphore)
        for url in web_sources
    )

    document_batches = await asyncio.gather(*tasks)
    documents = [
        document
        for batch in document_batches
        for document in batch
    ]

    if not documents:
        raise RuntimeError("No documents were loaded.")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=150,
        add_start_index=True,
    )

    chunks = splitter.split_documents(documents)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    records = [
        {
            "text": chunk.page_content,
            "metadata": chunk.metadata,
        }
        for chunk in chunks
    ]

    OUTPUT_FILE.write_text(
        json.dumps(records, indent=2, default=str),
        encoding="utf-8",
    )

    print(f"Loaded documents: {len(documents)}")
    print(f"Created chunks: {len(chunks)}")
    print(f"Saved output to: {OUTPUT_FILE}")


if __name__ == "__main__":
    asyncio.run(ingest())
