# filename: langchain_embed_upsert.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Awaitable, Callable

from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from pinecone import Pinecone


LOGGER = logging.getLogger("langchain.indexer")

RETRYABLE_STATUS_CODES = {408, 409, 429, 500, 502, 503, 504}
NON_RETRYABLE_ERROR_TYPES = (ValueError, TypeError, KeyError)


@dataclass(frozen=True)
class Settings:
    chunks_file: Path
    pinecone_index_name: str
    pinecone_namespace: str
    embedding_model: str
    embedding_dimensions: int
    embedding_batch_size: int
    max_concurrent_batches: int
    max_retries: int
    request_timeout: float
    base_backoff_seconds: float
    max_backoff_seconds: float

    @classmethod
    def from_environment(cls) -> "Settings":
        required = [
            "OPENAI_API_KEY",
            "PINECONE_API_KEY",
            "PINECONE_INDEX_NAME",
        ]
        missing = [name for name in required if not os.getenv(name)]

        if missing:
            raise RuntimeError(
                "Missing required environment variables: "
                + ", ".join(missing)
            )

        settings = cls(
            chunks_file=Path(
                os.getenv("CHUNKS_FILE", "processed/chunks.json")
            ),
            pinecone_index_name=os.environ["PINECONE_INDEX_NAME"],
            pinecone_namespace=os.getenv(
                "PINECONE_NAMESPACE",
                "rag-prod",
            ),
            embedding_model=os.getenv(
                "OPENAI_EMBEDDING_MODEL",
                "text-embedding-3-small",
            ),
            embedding_dimensions=int(
                os.getenv("EMBEDDING_DIMENSIONS", "512")
            ),
            embedding_batch_size=int(
                os.getenv("EMBEDDING_BATCH_SIZE", "64")
            ),
            max_concurrent_batches=int(
                os.getenv("MAX_CONCURRENT_BATCHES", "4")
            ),
            max_retries=int(os.getenv("MAX_RETRIES", "4")),
            request_timeout=float(
                os.getenv("REQUEST_TIMEOUT_SECONDS", "60")
            ),
            base_backoff_seconds=float(
                os.getenv("BASE_BACKOFF_SECONDS", "1")
            ),
            max_backoff_seconds=float(
                os.getenv("MAX_BACKOFF_SECONDS", "30")
            ),
        )

        if not 1 <= settings.embedding_batch_size <= 2048:
            raise ValueError(
                "EMBEDDING_BATCH_SIZE must be between 1 and 2048."
            )

        if settings.max_concurrent_batches < 1:
            raise ValueError(
                "MAX_CONCURRENT_BATCHES must be greater than zero."
            )

        return settings


def get_field(value: Any, name: str) -> Any:
    if isinstance(value, dict):
        return value.get(name)
    return getattr(value, name, None)


def normalize_metadata(metadata: dict[str, Any]) -> dict[str, Any]:
    normalized: dict[str, Any] = {}

    for key, value in metadata.items():
        clean_key = str(key).strip()

        if not clean_key or value is None:
            continue

        # LangChain/Pinecone will store page_content under its text key.
        if clean_key in {"text", "page_content"}:
            continue

        if isinstance(value, (str, int, float, bool)):
            normalized[clean_key] = value
        elif isinstance(value, list):
            items = [str(item) for item in value if item is not None]
            if items:
                normalized[clean_key] = items
        else:
            normalized[clean_key] = json.dumps(
                value,
                sort_keys=True,
                default=str,
            )

    return normalized


def create_document(
    record: dict[str, Any],
    record_number: int,
    run_id: str,
) -> tuple[Document, str]:
    text = str(record.get("text", "")).strip()

    if not text:
        raise ValueError(f"Record {record_number} contains no text.")

    raw_metadata = record.get("metadata") or {}

    if not isinstance(raw_metadata, dict):
        raise ValueError(
            f"Metadata for record {record_number} must be an object."
        )

    source = str(
        raw_metadata.get("source_ref")
        or raw_metadata.get("source_name")
        or raw_metadata.get("source")
        or "unknown"
    )

    provided_id = record.get("id") or raw_metadata.get("chunk_id")

    stable_material = json.dumps(
        {
            "source": source,
            "page": raw_metadata.get("page"),
            "start_index": raw_metadata.get("start_index"),
            "record_number": record_number,
            "text": text,
        },
        sort_keys=True,
        default=str,
    )

    generated_id = (
        "chunk-"
        + hashlib.sha256(
            stable_material.encode("utf-8")
        ).hexdigest()
    )

    chunk_id = str(provided_id or generated_id)

    document_metadata = normalize_metadata(raw_metadata)
    document_metadata.update(
        {
            "chunk_id": chunk_id,
            "source": source,
            "ingestion_run_id": run_id,
        }
    )

    return (
        Document(
            page_content=text,
            metadata=document_metadata,
        ),
        chunk_id,
    )


def load_documents(
    chunks_file: Path,
    run_id: str,
) -> tuple[list[Document], list[str]]:
    if not chunks_file.exists():
        raise FileNotFoundError(
            f"Chunks file does not exist: {chunks_file}"
        )

    payload = json.loads(
        chunks_file.read_text(encoding="utf-8")
    )

    if not isinstance(payload, list):
        raise ValueError("The chunks file must contain a JSON array.")

    documents: list[Document] = []
    ids: list[str] = []
    seen_ids: set[str] = set()

    for record_number, record in enumerate(payload):
        if not isinstance(record, dict):
            raise ValueError(
                f"Record {record_number} must be a JSON object."
            )

        document, chunk_id = create_document(
            record=record,
            record_number=record_number,
            run_id=run_id,
        )

        if chunk_id in seen_ids:
            raise ValueError(
                f"Duplicate chunk ID detected: {chunk_id}"
            )

        documents.append(document)
        ids.append(chunk_id)
        seen_ids.add(chunk_id)

    return documents, ids


def is_retryable(error: Exception) -> bool:
    if isinstance(error, NON_RETRYABLE_ERROR_TYPES):
        return False

    status_code = getattr(error, "status_code", None)

    if status_code is None:
        response = getattr(error, "response", None)
        status_code = getattr(response, "status_code", None)

    return status_code is None or status_code in RETRYABLE_STATUS_CODES


async def retry_async(
    operation: Callable[[], Awaitable[Any]],
    operation_name: str,
    settings: Settings,
) -> Any:
    for attempt in range(settings.max_retries + 1):
        try:
            return await operation()
        except Exception as error:
            final_attempt = attempt >= settings.max_retries

            if final_attempt or not is_retryable(error):
                raise

            exponential_delay = min(
                settings.max_backoff_seconds,
                settings.base_backoff_seconds * (2**attempt),
            )
            delay = min(
                settings.max_backoff_seconds,
                exponential_delay * random.uniform(0.5, 1.5),
            )

            LOGGER.warning(
                "%s failed on attempt %s. Retrying in %.2f seconds: %s",
                operation_name,
                attempt + 1,
                delay,
                error,
            )

            await asyncio.sleep(delay)

    raise RuntimeError(
        f"Retry loop exited unexpectedly: {operation_name}"
    )


async def index_batch(
    vector_store: PineconeVectorStore,
    batch_number: int,
    documents: list[Document],
    ids: list[str],
    settings: Settings,
) -> int:
    await retry_async(
        operation=lambda: vector_store.aadd_documents(
            documents=documents,
            ids=ids,
        ),
        operation_name=f"LangChain Pinecone batch {batch_number}",
        settings=settings,
    )

    LOGGER.info(
        "Indexed batch %s containing %s documents.",
        batch_number,
        len(documents),
    )

    return len(documents)


async def index_all_documents(
    vector_store: PineconeVectorStore,
    documents: list[Document],
    ids: list[str],
    settings: Settings,
) -> None:
    pending: set[asyncio.Task[int]] = set()
    total_indexed = 0

    try:
        for start in range(
            0,
            len(documents),
            settings.embedding_batch_size,
        ):
            end = start + settings.embedding_batch_size
            batch_documents = documents[start:end]
            batch_ids = ids[start:end]
            batch_number = (start // settings.embedding_batch_size) + 1

            pending.add(
                asyncio.create_task(
                    index_batch(
                        vector_store=vector_store,
                        batch_number=batch_number,
                        documents=batch_documents,
                        ids=batch_ids,
                        settings=settings,
                    )
                )
            )

            if len(pending) >= settings.max_concurrent_batches:
                done, pending = await asyncio.wait(
                    pending,
                    return_when=asyncio.FIRST_COMPLETED,
                )

                for task in done:
                    total_indexed += task.result()

        while pending:
            done, pending = await asyncio.wait(
                pending,
                return_when=asyncio.FIRST_COMPLETED,
            )

            for task in done:
                total_indexed += task.result()

    except BaseException:
        for task in pending:
            task.cancel()

        await asyncio.gather(
            *pending,
            return_exceptions=True,
        )
        raise

    LOGGER.info(
        "Indexing completed successfully. Total vectors: %s",
        total_indexed,
    )


def create_vector_store(
    settings: Settings,
) -> tuple[PineconeVectorStore, Any]:
    pinecone_client = Pinecone(
        api_key=os.environ["PINECONE_API_KEY"]
    )

    index_description = pinecone_client.describe_index(
        settings.pinecone_index_name
    )

    actual_dimension = get_field(index_description, "dimension")
    expected_dimension = settings.embedding_dimensions

    if actual_dimension is None:
        raise RuntimeError(
            "Could not determine the Pinecone index dimension."
        )

    if int(actual_dimension) != expected_dimension:
        raise RuntimeError(
            "Embedding dimension mismatch: "
            f"Pinecone index={actual_dimension}, "
            f"configured={expected_dimension}"
        )

    index_host = get_field(index_description, "host")

    if index_host:
        pinecone_index = pinecone_client.Index(host=index_host)
    else:
        pinecone_index = pinecone_client.Index(
            settings.pinecone_index_name
        )

    embeddings = OpenAIEmbeddings(
        model=settings.embedding_model,
        dimensions=settings.embedding_dimensions,
        chunk_size=settings.embedding_batch_size,
        max_retries=0,
        # request_timeout=settings.request_timeout,
    )

    vector_store = PineconeVectorStore(
        index=pinecone_index,
        embedding=embeddings,
        namespace=settings.pinecone_namespace,
    )

    return vector_store, pinecone_index


async def main() -> None:
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO").upper(),
        format=(
            "%(asctime)s %(levelname)s "
            "%(name)s %(message)s"
        ),
    )

    settings = Settings.from_environment()
    run_id = os.getenv("INGESTION_RUN_ID", "default")

    documents, ids = await asyncio.to_thread(
        load_documents,
        settings.chunks_file,
        run_id,
    )

    if not documents:
        raise RuntimeError("No documents were found to index.")

    LOGGER.info(
        "Loaded %s documents from %s.",
        len(documents),
        settings.chunks_file,
    )

    vector_store, _ = create_vector_store(settings)

    await index_all_documents(
        vector_store=vector_store,
        documents=documents,
        ids=ids,
        settings=settings,
    )


if __name__ == "__main__":
    asyncio.run(main())
