# filename: guard.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from __future__ import annotations

import hashlib
import logging
import math
import os
import re
import threading
import time
from collections import defaultdict, deque
from dataclasses import dataclass
from typing import Any, Mapping


class GuardrailError(Exception):
    """Raised when a request violates an application guardrail."""


@dataclass(frozen=True)
class GuardrailSettings:
    max_query_chars: int = 4000
    max_document_chars: int = 50000
    max_output_chars: int = 12000
    max_top_k: int = 20
    max_filter_depth: int = 4
    max_filter_items: int = 50
    rate_limit_per_minute: int = 120
    allowed_metadata_fields: frozenset[str] = frozenset(
        {
            "document_type",
            "source",
            "department",
            "classification",
            "language",
            "version",
            "effective_date",
        }
    )
    allowed_filter_operators: frozenset[str] = frozenset(
        {
            "$eq",
            "$ne",
            "$in",
            "$nin",
            "$gt",
            "$gte",
            "$lt",
            "$lte",
            "$exists",
        }
    )

    @classmethod
    def from_env(cls) -> "GuardrailSettings":
        configured_fields = os.getenv(
            "ALLOWED_METADATA_FIELDS",
            "document_type,source,department,classification,"
            "language,version,effective_date",
        )

        fields = frozenset(
            field.strip()
            for field in configured_fields.split(",")
            if field.strip()
        )

        return cls(
            max_query_chars=int(os.getenv("MAX_QUERY_CHARS", "4000")),
            max_document_chars=int(
                os.getenv("MAX_DOCUMENT_CHARS", "50000")
            ),
            max_output_chars=int(os.getenv("MAX_OUTPUT_CHARS", "12000")),
            max_top_k=int(os.getenv("MAX_TOP_K", "20")),
            max_filter_depth=int(os.getenv("MAX_FILTER_DEPTH", "4")),
            max_filter_items=int(os.getenv("MAX_FILTER_ITEMS", "50")),
            rate_limit_per_minute=int(
                os.getenv("RATE_LIMIT_PER_MINUTE", "120")
            ),
            allowed_metadata_fields=fields,
        )


@dataclass(frozen=True)
class ValidatedRetrieval:
    query: str
    top_k: int
    score_threshold: float
    pinecone_filter: dict[str, Any] | None


class SlidingWindowRateLimiter:
    def __init__(self, max_requests: int, window_seconds: int = 60):
        self.max_requests = max_requests
        self.window_seconds = window_seconds
        self._requests: dict[str, deque[float]] = defaultdict(deque)
        self._lock = threading.Lock()

    def check(self, key: str = "global") -> None:
        now = time.monotonic()
        cutoff = now - self.window_seconds

        with self._lock:
            timestamps = self._requests[key]

            while timestamps and timestamps[0] <= cutoff:
                timestamps.popleft()

            if len(timestamps) >= self.max_requests:
                raise GuardrailError(
                    "Rate limit exceeded. Please try again later."
                )

            timestamps.append(now)


class Guardrails:
    _blocked_query_patterns = (
        re.compile(
            r"(?is)\b(ignore|disregard|override).{0,100}"
            r"\b(previous|system|developer|assistant|instructions?)\b"
        ),
        re.compile(
            r"(?is)\b(reveal|print|show|provide).{0,100}"
            r"\b(system prompt|secrets?|api keys?|credentials?)\b"
        ),
    )

    _secret_patterns = (
        re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
        re.compile(
            r"(?i)\b(api[_ -]?key|token|secret|password)"
            r"\s*[:=]\s*\S+"
        ),
    )

    _control_characters = re.compile(
        r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]"
    )

    def __init__(
        self,
        settings: GuardrailSettings | None = None,
        logger: logging.Logger | None = None,
    ):
        self.settings = settings or GuardrailSettings.from_env()
        self.logger = logger or logging.getLogger(__name__)
        self._rate_limiter = SlidingWindowRateLimiter(
            self.settings.rate_limit_per_minute
        )

    def _clean_text(self, value: str, max_chars: int) -> str:
        if not isinstance(value, str):
            raise GuardrailError("Text input must be a string.")

        cleaned = self._control_characters.sub(" ", value)
        return cleaned[:max_chars].strip()

    def _redact_secrets(self, value: str) -> str:
        redacted = value

        for pattern in self._secret_patterns:
            if pattern.groups:
                redacted = pattern.sub(
                    lambda match: f"{match.group(1)}=[REDACTED]",
                    redacted,
                )
            else:
                redacted = pattern.sub("[REDACTED]", redacted)

        return redacted

    def validate_query(self, query: str) -> str:
        cleaned = self._clean_text(
            query,
            self.settings.max_query_chars,
        )

        if not cleaned:
            raise GuardrailError("The query cannot be empty.")

        normalized = re.sub(r"\s+", " ", cleaned)

        for pattern in self._blocked_query_patterns:
            if pattern.search(normalized):
                raise GuardrailError(
                    "The query contains a prohibited instruction pattern."
                )

        return normalized

    def sanitize_document(self, content: str) -> str:
        cleaned = self._clean_text(
            content,
            self.settings.max_document_chars,
        )
        return self._redact_secrets(cleaned)

    def sanitize_output(self, content: str) -> str:
        cleaned = self._clean_text(
            content,
            self.settings.max_output_chars,
        )
        cleaned = self._redact_secrets(cleaned)

        if not cleaned:
            raise GuardrailError("The model returned an empty answer.")

        return cleaned

    def _validate_scalar(self, value: Any) -> Any:
        if isinstance(value, bool):
            return value

        if isinstance(value, (int, float)):
            if isinstance(value, float) and not math.isfinite(value):
                raise GuardrailError(
                    "Metadata filter values must be finite."
                )
            return value

        if isinstance(value, str) and len(value) <= 500:
            return value

        raise GuardrailError(
            "Metadata filter values must be short strings or numbers."
        )

    def _validate_filter(
        self,
        metadata_filter: Mapping[str, Any],
        depth: int = 0,
    ) -> dict[str, Any]:
        if depth > self.settings.max_filter_depth:
            raise GuardrailError("Metadata filter nesting is too deep.")

        if not isinstance(metadata_filter, Mapping):
            raise GuardrailError("Metadata filter must be an object.")

        if len(metadata_filter) > self.settings.max_filter_items:
            raise GuardrailError("Metadata filter contains too many items.")

        validated: dict[str, Any] = {}

        for field, value in metadata_filter.items():
            if field in {"$and", "$or"}:
                if not isinstance(value, list) or not value:
                    raise GuardrailError(
                        f"{field} must contain a non-empty list."
                    )

                validated[field] = [
                    self._validate_filter(item, depth + 1)
                    for item in value
                ]
                continue

            if field.startswith("$"):
                raise GuardrailError(
                    f"Unsupported logical operator: {field}"
                )

            if field not in self.settings.allowed_metadata_fields:
                raise GuardrailError(
                    f"Metadata field is not allowed: {field}"
                )

            if isinstance(value, Mapping):
                operators: dict[str, Any] = {}

                for operator, operand in value.items():
                    if operator not in self.settings.allowed_filter_operators:
                        raise GuardrailError(
                            f"Unsupported filter operator: {operator}"
                        )

                    if operator in {"$in", "$nin"}:
                        if not isinstance(operand, list):
                            raise GuardrailError(
                                f"{operator} requires a list."
                            )

                        if len(operand) > self.settings.max_filter_items:
                            raise GuardrailError(
                                f"{operator} contains too many values."
                            )

                        operators[operator] = [
                            self._validate_scalar(item)
                            for item in operand
                        ]
                    elif operator == "$exists":
                        if not isinstance(operand, bool):
                            raise GuardrailError(
                                "$exists requires a Boolean value."
                            )

                        operators[operator] = operand
                    else:
                        operators[operator] = self._validate_scalar(
                            operand
                        )

                validated[field] = operators
            else:
                validated[field] = self._validate_scalar(value)

        return validated

    def validate_metadata_filter(
        self,
        metadata_filter: Mapping[str, Any] | None,
    ) -> dict[str, Any] | None:
        if metadata_filter is None:
            return None

        return self._validate_filter(metadata_filter)

    def validate_retrieval(
        self,
        query: str,
        metadata_filter: Mapping[str, Any] | None,
        top_k: int,
        score_threshold: float,
        request_id: str,
    ) -> ValidatedRetrieval:
        del request_id

        self._rate_limiter.check()

        validated_query = self.validate_query(query)

        if not isinstance(top_k, int):
            raise GuardrailError("top_k must be an integer.")

        if top_k < 1 or top_k > self.settings.max_top_k:
            raise GuardrailError(
                f"top_k must be between 1 and {self.settings.max_top_k}."
            )

        if not isinstance(score_threshold, (int, float)):
            raise GuardrailError(
                "score_threshold must be numeric."
            )

        if not 0 <= score_threshold <= 1:
            raise GuardrailError(
                "score_threshold must be between 0 and 1."
            )

        validated_filter = self.validate_metadata_filter(
            metadata_filter
        )

        return ValidatedRetrieval(
            query=validated_query,
            top_k=top_k,
            score_threshold=float(score_threshold),
            pinecone_filter=validated_filter,
        )

    def audit(
        self,
        request_id: str,
        query: str,
        retrieved_chunks: int,
        status: str = "success",
        error_code: str | None = None,
    ) -> None:
        query_hash = hashlib.sha256(
            query.encode("utf-8")
        ).hexdigest()[:16]

        event = {
            "event": "rag_request",
            "request_id": request_id,
            "query_hash": query_hash,
            "retrieved_chunks": retrieved_chunks,
            "status": status,
            "error_code": error_code,
        }

        self.logger.info("RAG audit event", extra={"rag_event": event})
