# filename: ret.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import math
import os
import random
import time
from dataclasses import dataclass
from typing import Any, Awaitable, Callable, Mapping, TypeVar

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from pinecone import Pinecone


from Guardrails import GuardrailError, GuardrailSettings, Guardrails
from Prompts import build_rag_messages

load_dotenv()


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

T = TypeVar("T")


@dataclass(frozen=True)
class RAGSettings:
    pinecone_index: str
    pinecone_namespace: str | None
    embedding_model: str
    chat_model: str
    top_k: int
    score_threshold: float
    max_context_chars: int

    @classmethod
    def from_env(cls) -> "RAGSettings":
        namespace = os.getenv("PINECONE_NAMESPACE")

        return cls(
            pinecone_index=os.environ["PINECONE_INDEX_NAME"],
            pinecone_namespace=namespace or None,
            embedding_model=os.getenv(
                "OPENAI_EMBEDDING_MODEL",
                "text-embedding-3-small",
            ),
            chat_model=os.getenv(
                "OPENAI_CHAT_MODEL",
                "gpt-4o-mini",
            ),
            top_k=int(os.getenv("RAG_TOP_K", "8")),
            score_threshold=float(
                os.getenv("RAG_SCORE_THRESHOLD", "0.7")
            ),
            max_context_chars=int(
                os.getenv("RAG_MAX_CONTEXT_CHARS", "24000")
            ),
        )


@dataclass(frozen=True)
class RAGRequest:
    query: str
    metadata_filter: Mapping[str, Any] | None = None
    top_k: int | None = None
    score_threshold: float | None = None
    request_id: str | None = None


@dataclass(frozen=True)
class RetrievedChunk:
    chunk_id: str
    content: str
    score: float
    metadata: Mapping[str, Any]


@dataclass(frozen=True)
class RAGResponse:
    answer: str
    citations: list[dict[str, Any]]
    retrieved_chunks: int
    request_id: str


def make_request_id(value: str | None) -> str:
    if value:
        return value

    seed = f"{time.time_ns()}:{random.random()}".encode()
    return hashlib.sha256(seed).hexdigest()[:16]


async def with_retry(
    operation: Callable[[], Awaitable[T]],
    attempts: int = 3,
) -> T:
    for attempt in range(attempts):
        try:
            return await operation()
        except Exception:
            if attempt == attempts - 1:
                raise

            await asyncio.sleep(min(2**attempt, 8) + random.random())

    raise RuntimeError("The operation failed after all retries.")


class EnterpriseRAG:
    def __init__(
        self,
        settings: RAGSettings,
        vector_store: PineconeVectorStore,
        llm: ChatOpenAI,
        guardrails: Guardrails,
    ):
        self.settings = settings
        self.vector_store = vector_store
        self.llm = llm
        self.guardrails = guardrails

    @classmethod
    async def create(cls) -> "EnterpriseRAG":
        settings = RAGSettings.from_env()

        pinecone = Pinecone(
            api_key=os.environ["PINECONE_API_KEY"]
        )
        index = pinecone.Index(settings.pinecone_index)
        print(f"pine cone index created : {settings.pinecone_index}")
        await asyncio.to_thread(index.describe_index_stats)

        embeddings = OpenAIEmbeddings(
            model=settings.embedding_model,
            api_key=lambda: os.environ["OPENAI_API_KEY"],
            dimensions=512,
        )

        vector_store = PineconeVectorStore(
            index=index,
            embedding=embeddings,
            namespace=settings.pinecone_namespace,
        )

        llm = ChatOpenAI(
            model=settings.chat_model,
            temperature=0,
            api_key=lambda: os.environ["OPENAI_API_KEY"],
        )

        return cls(
            settings=settings,
            vector_store=vector_store,
            llm=llm,
            guardrails=Guardrails(
                GuardrailSettings.from_env()
            ),
        )

    def _safe_metadata(
        self,
        metadata: Mapping[str, Any],
    ) -> dict[str, Any]:
        allowed = (
            set(self.guardrails.settings.allowed_metadata_fields)
            | {"chunk_id", "source", "page"}
        )

        return {
            str(key): value
            for key, value in metadata.items()
            if str(key) in allowed
        }

    def _prepare_context(
        self,
        matches: list[tuple[Document, float]],
        score_threshold: float,
    ) -> tuple[list[RetrievedChunk], str]:
        chunks: list[RetrievedChunk] = []
        context_parts: list[str] = []
        current_chars = 0

        for rank, (document, raw_score) in enumerate(
            matches,
            start=1,
        ):
            score = float(raw_score)

            if not math.isfinite(score) or score < score_threshold:
                continue

            content = self.guardrails.sanitize_document(
                document.page_content
            )

            if not content:
                continue

            original_metadata = dict(document.metadata)
            metadata = self._safe_metadata(original_metadata)

            chunk_id = str(
                metadata.get(
                    "chunk_id",
                    metadata.get("source", f"chunk-{rank}"),
                )
            )

            remaining = self.settings.max_context_chars - current_chars

            if remaining <= 0:
                break

            content = content[:remaining]

            chunks.append(
                RetrievedChunk(
                    chunk_id=chunk_id,
                    content=content,
                    score=score,
                    metadata=metadata,
                )
            )

            context_parts.append(
                f"[{chunk_id} | score={score:.3f}]\n{content}"
            )

            current_chars += len(content)

        return chunks, "\n\n".join(context_parts)

    @staticmethod
    def _message_text(content: Any) -> str:
        if isinstance(content, str):
            return content

        if isinstance(content, list):
            parts: list[str] = []

            for item in content:
                if isinstance(item, Mapping):
                    text = item.get("text")

                    if text:
                        parts.append(str(text))
                else:
                    parts.append(str(item))

            return "\n".join(parts)

        return str(content)

    async def _generate_answer(
        self,
        query: str,
        context: str,
    ) -> str:
        response = await with_retry(
            lambda: self.llm.ainvoke(
                build_rag_messages(
                    query=query,
                    context=context,
                )
            )
        )

        answer = self._message_text(response.content)
        return self.guardrails.sanitize_output(answer)

    async def _retrieve(
        self,
        query: str,
        top_k: int,
        metadata_filter: Mapping[str, Any] | None,
    ) -> list[tuple[Document, float]]:
        if metadata_filter:
            return await (
                self.vector_store.asimilarity_search_with_score(
                    query=query,
                    k=top_k,
                    filter=dict(metadata_filter),
                )
            )

        return await (
            self.vector_store.asimilarity_search_with_score(
                query=query,
                k=top_k,
            )
            # retriev = self.vector_store.as_retriever(search_kwargs={"k":3})
            # docs = retriev.invoke(query)
        )

    async def retrieve_and_generate(
        self,
        request: RAGRequest,
    ) -> RAGResponse:
        request_id = make_request_id(request.request_id)
        retrieved_count = 0

        try:
            top_k = (
                request.top_k
                if request.top_k is not None
                else self.settings.top_k
            )

            score_threshold = (
                request.score_threshold
                if request.score_threshold is not None
                else self.settings.score_threshold
            )

            validated = self.guardrails.validate_retrieval(
                query=request.query,
                metadata_filter=request.metadata_filter,
                top_k=top_k,
                score_threshold=score_threshold,
                request_id=request_id,
            )

            matches = await with_retry(
                lambda: self._retrieve(
                    query=validated.query,
                    top_k=validated.top_k,
                    metadata_filter=validated.pinecone_filter,
                )
            )

            chunks, context = self._prepare_context(
                matches=matches,
                score_threshold=validated.score_threshold,
            )
            retrieved_count = len(chunks)

            if not chunks:
                answer = (
                    "I could not find relevant information in "
                    "the knowledge base."
                )
            else:
                answer = await self._generate_answer(
                    query=validated.query,
                    context=context,
                )

            citations = [
                {
                    "chunk_id": chunk.chunk_id,
                    "score": round(chunk.score, 4),
                    "metadata": dict(chunk.metadata),
                }
                for chunk in chunks
            ]

            self.guardrails.audit(
                request_id=request_id,
                query=validated.query,
                retrieved_chunks=retrieved_count,
            )

            return RAGResponse(
                answer=answer,
                citations=citations,
                retrieved_chunks=retrieved_count,
                request_id=request_id,
            )

        except GuardrailError:
            self.guardrails.audit(
                request_id=request_id,
                query=request.query,
                retrieved_chunks=retrieved_count,
                status="blocked",
                error_code="GuardrailError",
            )
            raise

        except Exception as exc:
            self.guardrails.audit(
                request_id=request_id,
                query=request.query,
                retrieved_chunks=retrieved_count,
                status="error",
                error_code=type(exc).__name__,
            )
            logger.exception("RAG request failed.")
            raise


async def main() -> None:
    rag = await EnterpriseRAG.create()

    response = await rag.retrieve_and_generate(
        RAGRequest(
            query="Tell me about RAG testing",
            metadata_filter=None,
            top_k=5,
            score_threshold=0.7,
            # metadata_filter={
            #     "document_type": {
            #         "$in": ["policy", "procedure"]
            #     }
            # },
        )
    )

    print(
        json.dumps(
            {
                "answer": response.answer,
                "citations": response.citations,
                "retrieved_chunks": response.retrieved_chunks,
                "request_id": response.request_id,
            },
            indent=2,
            default=str,
        )
    )
    
if __name__ == "__main__":
    asyncio.run(main())
